modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Harveykang/AsyncParticles/issues"
license = "MIT"

[[mods]]
modId = "asyncparticles"
version = "${version}"
displayName = "AsyncParticles"
authors = ""
description = '''

'''
logoFile = "assets/asyncparticles/icon.png"

[[dependencies.asyncparticles]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.asyncparticles]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"
