# Done to increase the memory available to Gradle.
loom.ignoreDependencyLoomVersionValidation=true
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true
# Mod properties
mod_version=0.26.3.2-alpha.2
maven_group=fun.qu_an.minecraft
archives_name=AsyncParticles
enabled_platforms=fabric
# Minecraft properties
minecraft_version=26.3-snapshot-7
# Dependencies
# https://fabricmc.net/develop/
fabric_loader_version=0.19.3
fabric_api_version=0.156.3+26.3
# https://neoforged.net/
neoforge_version=26.2.0.40-beta

snapshot=false

enable_vulkan=false
vk_debug=true
glsl_validator=D:/Program Files/VulkanSDK/Bin/glslangValidator.exe
vk_layer_path=D:/Program Files/VulkanSDK/Bin/
