#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer Counters {
    uint inCount;
    uint inOverflow;
};

layout(binding = 1, std430) buffer IndirectBuffer {
    uint cmd[10];
};

void main() {
    cmd[0] = (inCount - inOverflow) * 4u;
    cmd[1] = 1u;
    cmd[2] = inOverflow * 4u;
    cmd[3] = inOverflow * 4u;
    cmd[4] = 0u;

    cmd[5] = inOverflow * 4u;
    cmd[6] = 1u;
    cmd[7] = 0u;
    cmd[8] = 0u;
    cmd[9] = 0u;
}
