modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Harveykang/AsyncParticles/issues"
license = "MIT"

[[mods]]
modId = "asyncparticles"
version = "${version}"
displayName = "AsyncParticles"
authors = "Harvey_Husky"
description = '''
'''
logoFile = "assets/asyncparticles/icon.png"

[[dependencies.asyncparticles]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.asyncparticles]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5]"
ordering = "NONE"
side = "CLIENT"

#[[dependencies.asyncparticles]]
#modId = "mixinextras"
#mandatory = true
#versionRange = "[0.4.1,)"
#ordering = "NONE"
#side = "CLIENT"
#
#[[dependencies.asyncparticles]]
#modId = "mixinsquared"
#mandatory = true
#versionRange = "(0.1.999,)"
#ordering = "NONE"
#side = "CLIENT"

[[mixins]]
config = "asyncparticles-common.mixins.json"

[[mixins]]
config = "asyncparticles-common_legacy_mod_compat.mixins.json"

[[mixins]]
config = "asyncparticles-neoforge.mixins.json"

[[mixins]]
config = "asyncparticles.target-modifier.mixins.json"
